name: Python checks üêç

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - backend/backlog_app/**

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: "backend/.python-version"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        working-directory: backend
        run: uv sync --locked --all-extras --dev

      - name: Run black
        working-directory: backend
        run: uv run black . --check --diff

      - name: Run isort
        working-directory: backend
        run: uv run isort . --check-only --diff
